# --- Stage 1: Build the application with Maven ---
# This stage builds your application from source.
FROM maven:3.8-openjdk-11 AS build

WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn package -DskipTests

# --- Stage 2: Create the final, self-contained image ---
# This stage creates the small, runnable image.
FROM openjdk:11-jre-slim

WORKDIR /app

# Copy the executable JAR from the build stage
COPY --from=build /app/target/mqtt-chat-terminal-1.0-SNAPSHOT.jar /app/app.jar

COPY config.yml .


ENTRYPOINT ["java", "--add-opens=java.base/sun.nio.ch=ALL-UNNAMED", "-jar", "/app/app.jar", "server", "config.yml"]
